import type { DigitalHuman, QuickAction } from "../types";
import {
  ALERT_ANALYSIS_MCP_SERVICE,
  DATA_RISK_ASSESSMENT_MCP_SERVICE,
  DUAL_NEW_ASSESSMENT_MCP_SERVICE,
  GO_LIVE_SECURITY_ASSESSMENT_MCP_SERVICE,
  INCIDENT_DRILL_MCP_SERVICE,
  INCIDENT_RESPONSE_MCP_SERVICE,
  NETWORK_RISK_ASSESSMENT_MCP_SERVICE,
  SECURITY_BULLETIN_MCP_SERVICE,
  SECURITY_TRAINING_MCP_SERVICE,
} from "../services/mcpSettings";

export const digitalHumans: DigitalHuman[] = [
  {
    id: "network-security-risk-assessment",
    name: "网安风评数字员工",
    role: "网络安全风险评估",
    description: "辅助开展检查项对标、证据整理、风险分析和整改建议。",
    accent: "emerald",
    mcpService: NETWORK_RISK_ASSESSMENT_MCP_SERVICE,
    status: "pending",
  },
  {
    id: "data-security-risk-assessment",
    name: "数安风评数字员工",
    role: "数据安全风险评估",
    description: "辅助梳理数据处理活动，开展合规对比、证据留痕和风险分析。",
    accent: "teal",
    mcpService: DATA_RISK_ASSESSMENT_MCP_SERVICE,
    status: "pending",
  },
  {
    id: "system-go-live-security-assessment",
    name: "上线安评数字员工",
    role: "新系统上线安全评估",
    description: "辅助开展上线前安全检查、证据核验、风险判断和遗留问题确认。",
    accent: "blue",
    mcpService: GO_LIVE_SECURITY_ASSESSMENT_MCP_SERVICE,
    status: "pending",
  },
  {
    id: "dual-new-assessment",
    name: "双新安评数字员工",
    role: "新技术新业务评估",
    description: "辅助识别新技术、新业务中的网络、数据、供应链和合规风险。",
    accent: "primary",
    mcpService: DUAL_NEW_ASSESSMENT_MCP_SERVICE,
    status: "pending",
  },
  {
    id: "incident-response",
    name: "应急响应数字员工",
    role: "安全事件应急响应",
    description: "辅助完成事件信息采集、初步研判、响应建议和处置记录。",
    accent: "crimson",
    mcpService: INCIDENT_RESPONSE_MCP_SERVICE,
    status: "pending",
  },
  {
    id: "incident-drill",
    name: "应急演练数字员工",
    role: "安全应急演练",
    description: "辅助形成演练方案、场景脚本、过程记录、评分和改进计划。",
    accent: "indigo",
    mcpService: INCIDENT_DRILL_MCP_SERVICE,
    status: "pending",
  },
  {
    id: "training-service",
    name: "安全培训数字员工",
    role: "安全培训服务",
    description: "辅助生成培训大纲、课件讲稿、互动练习、测试题和培训总结。",
    accent: "amber",
    mcpService: SECURITY_TRAINING_MCP_SERVICE,
    status: "pending",
  },
  {
    id: "security-bulletin-service",
    name: "安全通告数字员工",
    role: "安全通告服务",
    description: "辅助核验漏洞与威胁信息，生成安全通告、排查建议和整改说明。",
    accent: "soft",
    mcpService: SECURITY_BULLETIN_MCP_SERVICE,
    status: "pending",
  },
  {
    id: "alert-analysis",
    name: "威胁研判数字员工",
    role: "安全告警威胁研判",
    description: "处理告警、日志、截图和流量材料，输出研判结论与处置建议。",
    accent: "indigo",
    mcpService: ALERT_ANALYSIS_MCP_SERVICE,
    status: "pending",
    disabledReason: "请在数字员工管理中配置并启用威胁研判服务",
  },
];

export const quickActions: QuickAction[] = digitalHumans.map((human) => ({
  id: human.id,
  title: human.name,
  prompt: "",
  tone: human.accent,
  mcpService: human.mcpService,
  status: human.status,
  disabledReason: human.disabledReason,
}));
